### ISSUE TITLE
Typo on the VisualStudioGallery page

### ISSUE THREAD

**Issue by StefanOssendorf** [jsakamoto/xUnitTestCodeSnippets#3]
Hi,

I've found a typo on the extension site: [xUnit Code Snippets](https://visualstudiogallery.msdn.microsoft.com/032cd260-d4cd-4849-adff-648ea9a28265?SRC=VSIDE)
There is "afa**x**t" and not "afact"

**Comment by jsakamoto** [comment]
I fixed it.
Thank you for your report!

**Comment by StefanOssendorf** [comment]
You're welcome :)
