### ISSUE TITLE
Cannot install on latest VS 2019 (16.1)

### ISSUE THREAD

**Issue by tiesmaster** [jsakamoto/xUnitTestCodeSnippets#4]
Should VS 2019 Community be blocked? I'm getting an error installing it on this SKU. Will dig into this more tonight, if it's a problem on my side, but already wanted to start the discussion on it.

![image](https://user-images.githubusercontent.com/460904/58877993-7ecb0800-86d2-11e9-85ee-82d11373e326.png)

**Comment by tiesmaster** [comment]
Wait, now I see it in the [logs](https://pastebin.com/k6f0F2ya):

````
04/06/2019 14:09:17 - 	Supported Products : 
04/06/2019 14:09:17 - 		Microsoft.VisualStudio.Community
04/06/2019 14:09:17 - 			Version : [11.0,16.0]
04/06/2019 14:09:17 - 		Microsoft.VisualStudio.Pro
04/06/2019 14:09:17 - 			Version : [11.0,16.0]
04/06/2019 14:09:17 - 		Microsoft.VisualStudio.Enterprise
04/06/2019 14:09:17 - 			Version : [11.0,16.0]
````

But I'm running 16.1 (`16.1.1`). I'm guessing that's the problem, can we maybe increase the supported version to include 16.1? I can put in a PR, if you want.

**Comment by jsakamoto** [comment]
Oh, thank you very much for your report 👍 

Welcome your PR!
I'll test it and merge it.

Thanks!

**Comment by tiesmaster** [comment]
Awesome!! I've opened up #5 to fix it. Tested it locally, and works fine here 🎉 (really happy to see "my" snippets back 😄
