### ISSUE TITLE
Is it possible to create a macro for MemberData and ClassData?

### ISSUE THREAD

**Issue by philippedurocher** [jsakamoto/xUnitTestCodeSnippets#9]
Thank your for the snippets you made, I'm very please with it.

Would it be possible to generate the placeholder code for ClassData and MemberData?

Thank you!

**Comment by jsakamoto** [comment]
@philippedurocher 
Thank you for your proposal!
So, could you make your proposal more specifically what you want to?
What code would be better to be generated?
I'll consider trying to implement that!

**Comment by philippedurocher** [comment]
macro : xcdata
cursor positionned on class name (TestData)
generates this snippet
```
public class TestData : IEnumerable<object[]>
{
    public IEnumerator<object[]> GetEnumerator()
    {
        yield return new object[] { };
    }

    IEnumerator IEnumerable.GetEnumerator() => GetEnumerator();
}
```

macro : xmdata
cursor positionned on property name (Data)
generates this snippet
```
    public static IEnumerable<object[]> Data => new List<object[]>
    {
        new object[] { },
    };
```

My examples are based on this Andrew Lock's post : https://andrewlock.net/creating-parameterised-tests-in-xunit-with-inlinedata-classdata-and-memberdata/

Do you think it's possible?

**Comment by jsakamoto** [comment]
@philippedurocher 

I implemented it and published it.

- https://marketplace.visualstudio.com/items?itemName=jsakamoto.xUnitCodeSnippets

Could you try it out?

**Comment by philippedurocher** [comment]
It's perfect, thank you!
